### PR TITLE
License

### PR DESCRIPTION
**Pull request by jmacdotorg**
Adding acknowledgment and license information for a number of included projects, as well as overall copyright information.

Based on the `quixe` branch because I didn't think of adding this until I added Quixe, even though I'd already rolled in two other projects years ago...

### CODE REVIEW

**Comment by adherzog** [comment]
* This doesn't seem to indicate what license the IFComp software uses.

 * I'd like the see the copyright and IFComp license listed directly in the README.

 * The links on LICENSE.MD to the various licenses don't work when viewing the file on GitHub.

 * Is there somebody on the team that has experience (or legal knowledge about) applying licenses like this? I don't know enough about it to say whether this is the correct way to go about it.

 * Could you either update or remove the AUTHOR and LICENSE sections of the code itself, where it currently says "This library is free software. You can redistribute it and/or modify it under the same terms as Perl itself." It should include the copyright and proper license, or nothing at all (I think.)

**Comment by jmacdotorg** [comment]
Uhhhhhh I don't know why this closed. I thought I'd be clever by rebasing it to master, but I should learn to never be clever. (I will never learn to never be clever, don't worry.)

**Comment by jmacdotorg** [comment]
w/e. I'll treat this as rejected for the reasons that @adherzog raised, and put it back in the oven.

**Comment by jmacdotorg** [comment]
Re-opening this with new commits that respond to @adherzog's requests from July 31.

Clarifying a couple of points:

This does not specify a open-source license, because it does not have an open-source license to specify. (Maybe that will change in the future, but it is the case now.)

IFTF's legal counsel has reviewed the license document and suggested a rewording of the initial ownership statement, which these most recent commits bring into account.

**Pull request merged**
