### PR TITLE
Add Quixe interpreter

### PR DESCRIPTION
**Pull request by jmacdotorg**
This adds [the Quixe interpreter](https://github.com/erkyrath/quixe), version 2.1.6, to the project. Consequently, it removes the Glulx-compatible Parchment files from the project (while preserving Parchment for use with Z-code games).

Uploaded Glulx-based games that don't themselves provide a Quixe interpreter will use ours. It doesn't make use of Quixe's native transcript recording, but I intend to add this in a future (pre-October) update.

This patch also improves and clarifies the contents of root/static/interpreter, putting everything into three neat subdirectories (for parchment, quixe, and the transcript recorder), instead of its current muddle.

Addresses #66.

### CODE REVIEW

**Comment by taskboy3000** [comment]
For what it's worth, you might consider refactoring the way the base HTML file for quixe is generated. You can make a controller smart enough to generate this HTML and save it to the right place. That is the Railsy way to handle this.

**Comment by jmacdotorg** [comment]
@taskboy3000, I get you, but I want this to work outside of the web application per se. In other words, I want to (and often do) call a script that re-generates the pages in question, as needed. I'd rather not have to artificially hit the website via script to have the same effect.

**Comment by curiousdannii** [comment]
The version of Parchment in this branch is extremely old, and probably somewhat buggy. Why was zvm.min.js deleted?

**Comment by jmacdotorg** [comment]
curiousdannii: Could you please open a new issue with your recommendation for which commit or branch of Parchment to use for Z-code games? I'd love to update IFComp's copy.

As to your question... well, it's a good question. I don't consciously remember deleting zvm.min.js, so it may have been an oversight on my part while I rearranged IFComp's interpreter files. That said, it looks like that file is (at least in the version IFComp uses) invoked only by parchment.debug.js, which in turn is not invoked by anything?

**Pull request merged**
