### PR TITLE
Update terps

### PR DESCRIPTION
**Pull request by curiousdannii**
Updates for Glkote and Quixe. ZVM still to come (are there any entries this year? otherwise I won't make it a priority)

Initial support for stylehints and garglk text formatting.

Have not modified the generated HTML yet, could do with some help.

### CODE REVIEW

**Comment by jmacdotorg** [comment]
This PR adds a new directory for glkote, and I'm not clear as to why. The one glkote library (as well as the jquery library) in the main branch is within the quixe directory, here: https://github.com/iftechfoundation/ifcomp/tree/master/IFComp/root/static/interpreter/quixe/lib Should these files go there, instead?

**Comment by curiousdannii** [comment]
Just because it will be used by ZVM and potentially any other terps we add. I'll clean up the other files.

**Comment by jmacdotorg** [comment]
OK, if they're commonly used libraries that makes sense.

In that case you'll want to update the generated HTML, just as you say. You can find it in the file IFComp/lib/Schema/Result/Entry.pm. Do a search for "src" and you'll find lots of interesting stuff, some of which will need updating.

**Comment by curiousdannii** [comment]
I think this might work now. I haven't tested it.

**Comment by jmacdotorg** [comment]
This seems to work pretty well, actually!

The one issue I can find is that the Quixe header-mangling code doesn't add in all the new <script> tags necessary to pull in new, apparently refactored libraries.

I would suggest adding something like this, right before the final `$play_file->spew($play_html);` line of the `_mangle_quixe_head` method definition:

```
    # Throw in some more <script> tags pointing at modern libraries.
    $play_html =~ s{</head>}
                   {<script src="/static/interpreter/glkote/dialog.js"></script>
<script src="/static/interpreter/glkote/glkapi.js"></script>
<script src="/static/interpreter/quixe/gi_dispa.js"></script>
<script src="/static/interpreter/glkote/gi_load.js"></script>
</head>};
```

What do you think?

**Comment by curiousdannii** [comment]
Maybe I should just concat them again - I split them up because it's a bit clearer for working on it, and because one file (gi_load) would be shared by ZVM, but maybe concating them would just be better.

**Comment by jmacdotorg** [comment]
For the purposes of easier future updating, I’d prefer to keep them in whatever shape the Parchment project keeps them. I don’t mind separate files (and a few more script tags) if that ends up tracking better with Parchment development.

**Comment by curiousdannii** [comment]
The comp site doesn't look like it supports HTTP2 currently, so concatting will be better.

Ideally a build system would do this instead of me manually. Maybe in the future ;)

**Comment by jmacdotorg** [comment]
Looks good to me. Thanks!

**Pull request merged**
